# Generated by Django 3.1 on 2020-09-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200907_0944'),
        ('recipes', '0004_auto_20200909_1357'),
    ]

    operations = [
    ]
