# Generated by Django 3.1 on 2020-09-14 09:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200909_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AlterModelManagers(
            name='favorite',
            managers=[
                ('favorite', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='purchase',
            managers=[
                ('purchase', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
                ('recipes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='recipes.Tag', verbose_name='Теги'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('ingredient', 'amount', 'recipe')},
        ),
    ]
